import type { CanonicalCategory } from "@/lib/catalog/types";

export const expenseCatalog = [
  {
    id: "expense-food",
    name: "Food",
    parentId: null,
    kind: "expense",
    icon: "utensils",
    color: "orange",
    isLeaf: false,
  },
  {
    id: "expense-food-rice",
    name: "Rice",
    parentId: "expense-food",
    kind: "expense",
    icon: "wheat",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-vegetables",
    name: "Vegetables",
    parentId: "expense-food",
    kind: "expense",
    icon: "carrot",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-fruits",
    name: "Fruits",
    parentId: "expense-food",
    kind: "expense",
    icon: "apple",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-meat",
    name: "Meat",
    parentId: "expense-food",
    kind: "expense",
    icon: "beef",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-chicken",
    name: "Chicken",
    parentId: "expense-food",
    kind: "expense",
    icon: "drumstick",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-fish",
    name: "Fish",
    parentId: "expense-food",
    kind: "expense",
    icon: "fish",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-eggs",
    name: "Eggs",
    parentId: "expense-food",
    kind: "expense",
    icon: "egg",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-cooking-oil",
    name: "Cooking Oil",
    parentId: "expense-food",
    kind: "expense",
    icon: "droplet",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-sugar",
    name: "Sugar",
    parentId: "expense-food",
    kind: "expense",
    icon: "package",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-salt",
    name: "Salt",
    parentId: "expense-food",
    kind: "expense",
    icon: "package",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-flour",
    name: "Flour",
    parentId: "expense-food",
    kind: "expense",
    icon: "package",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-milk",
    name: "Milk",
    parentId: "expense-food",
    kind: "expense",
    icon: "milk",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-coffee",
    name: "Coffee",
    parentId: "expense-food",
    kind: "expense",
    icon: "coffee",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-tea",
    name: "Tea",
    parentId: "expense-food",
    kind: "expense",
    icon: "cup-soda",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-snacks",
    name: "Snacks",
    parentId: "expense-food",
    kind: "expense",
    icon: "cookie",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-instant-noodles",
    name: "Instant Noodles",
    parentId: "expense-food",
    kind: "expense",
    icon: "soup",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-food-bottled-water",
    name: "Bottled Water",
    parentId: "expense-food",
    kind: "expense",
    icon: "bottle-water",
    color: "orange",
    isLeaf: true,
  },
  {
    id: "expense-transportation",
    name: "Transportation",
    parentId: null,
    kind: "expense",
    icon: "car",
    color: "blue",
    isLeaf: false,
  },
  {
    id: "expense-transportation-fuel",
    name: "Fuel",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "fuel",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-transportation-parking",
    name: "Parking",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "parking-circle",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-transportation-toll",
    name: "Toll",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "badge-dollar-sign",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-transportation-public-transport",
    name: "Public Transport",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "bus",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-transportation-ride-hailing",
    name: "Ride Hailing",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "map-pin",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-transportation-vehicle-maintenance",
    name: "Vehicle Maintenance",
    parentId: "expense-transportation",
    kind: "expense",
    icon: "wrench",
    color: "blue",
    isLeaf: true,
  },
  {
    id: "expense-housing",
    name: "Housing",
    parentId: null,
    kind: "expense",
    icon: "home",
    color: "sky",
    isLeaf: false,
  },
  {
    id: "expense-housing-rent",
    name: "Rent",
    parentId: "expense-housing",
    kind: "expense",
    icon: "key-round",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-housing-electricity",
    name: "Electricity",
    parentId: "expense-housing",
    kind: "expense",
    icon: "zap",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-housing-water",
    name: "Water",
    parentId: "expense-housing",
    kind: "expense",
    icon: "droplets",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-housing-internet",
    name: "Internet",
    parentId: "expense-housing",
    kind: "expense",
    icon: "wifi",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-housing-gas",
    name: "Gas",
    parentId: "expense-housing",
    kind: "expense",
    icon: "flame",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-housing-household-supplies",
    name: "Household Supplies",
    parentId: "expense-housing",
    kind: "expense",
    icon: "shopping-basket",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "expense-health",
    name: "Health",
    parentId: null,
    kind: "expense",
    icon: "heart-pulse",
    color: "rose",
    isLeaf: false,
  },
  {
    id: "expense-health-medicine",
    name: "Medicine",
    parentId: "expense-health",
    kind: "expense",
    icon: "pill",
    color: "rose",
    isLeaf: true,
  },
  {
    id: "expense-health-doctor",
    name: "Doctor",
    parentId: "expense-health",
    kind: "expense",
    icon: "stethoscope",
    color: "rose",
    isLeaf: true,
  },
  {
    id: "expense-health-hospital",
    name: "Hospital",
    parentId: "expense-health",
    kind: "expense",
    icon: "hospital",
    color: "rose",
    isLeaf: true,
  },
  {
    id: "expense-health-insurance",
    name: "Insurance",
    parentId: "expense-health",
    kind: "expense",
    icon: "shield-check",
    color: "rose",
    isLeaf: true,
  },
  {
    id: "expense-health-vitamins",
    name: "Vitamins",
    parentId: "expense-health",
    kind: "expense",
    icon: "plus-circle",
    color: "rose",
    isLeaf: true,
  },
  {
    id: "expense-education",
    name: "Education",
    parentId: null,
    kind: "expense",
    icon: "graduation-cap",
    color: "lime",
    isLeaf: false,
  },
  {
    id: "expense-education-tuition",
    name: "Tuition",
    parentId: "expense-education",
    kind: "expense",
    icon: "school",
    color: "lime",
    isLeaf: true,
  },
  {
    id: "expense-education-books",
    name: "Books",
    parentId: "expense-education",
    kind: "expense",
    icon: "book-open",
    color: "lime",
    isLeaf: true,
  },
  {
    id: "expense-education-courses",
    name: "Courses",
    parentId: "expense-education",
    kind: "expense",
    icon: "monitor-play",
    color: "lime",
    isLeaf: true,
  },
  {
    id: "expense-education-school-supplies",
    name: "School Supplies",
    parentId: "expense-education",
    kind: "expense",
    icon: "pencil-ruler",
    color: "lime",
    isLeaf: true,
  },
  {
    id: "expense-shopping",
    name: "Shopping",
    parentId: null,
    kind: "expense",
    icon: "shopping-bag",
    color: "fuchsia",
    isLeaf: false,
  },
  {
    id: "expense-shopping-clothing",
    name: "Clothing",
    parentId: "expense-shopping",
    kind: "expense",
    icon: "shirt",
    color: "fuchsia",
    isLeaf: true,
  },
  {
    id: "expense-shopping-electronics",
    name: "Electronics",
    parentId: "expense-shopping",
    kind: "expense",
    icon: "smartphone",
    color: "fuchsia",
    isLeaf: true,
  },
  {
    id: "expense-shopping-furniture",
    name: "Furniture",
    parentId: "expense-shopping",
    kind: "expense",
    icon: "sofa",
    color: "fuchsia",
    isLeaf: true,
  },
  {
    id: "expense-shopping-personal-care",
    name: "Personal Care",
    parentId: "expense-shopping",
    kind: "expense",
    icon: "sparkles",
    color: "fuchsia",
    isLeaf: true,
  },
  {
    id: "expense-entertainment",
    name: "Entertainment",
    parentId: null,
    kind: "expense",
    icon: "film",
    color: "indigo",
    isLeaf: false,
  },
  {
    id: "expense-entertainment-movies",
    name: "Movies",
    parentId: "expense-entertainment",
    kind: "expense",
    icon: "clapperboard",
    color: "indigo",
    isLeaf: true,
  },
  {
    id: "expense-entertainment-games",
    name: "Games",
    parentId: "expense-entertainment",
    kind: "expense",
    icon: "gamepad-2",
    color: "indigo",
    isLeaf: true,
  },
  {
    id: "expense-entertainment-streaming",
    name: "Streaming",
    parentId: "expense-entertainment",
    kind: "expense",
    icon: "play-square",
    color: "indigo",
    isLeaf: true,
  },
  {
    id: "expense-entertainment-hobbies",
    name: "Hobbies",
    parentId: "expense-entertainment",
    kind: "expense",
    icon: "palette",
    color: "indigo",
    isLeaf: true,
  },
  {
    id: "expense-financial",
    name: "Financial",
    parentId: null,
    kind: "expense",
    icon: "landmark",
    color: "teal",
    isLeaf: false,
  },
  {
    id: "expense-financial-savings",
    name: "Savings",
    parentId: "expense-financial",
    kind: "expense",
    icon: "piggy-bank",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "expense-financial-investments",
    name: "Investments",
    parentId: "expense-financial",
    kind: "expense",
    icon: "trending-up",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "expense-financial-taxes",
    name: "Taxes",
    parentId: "expense-financial",
    kind: "expense",
    icon: "receipt-text",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "expense-financial-bank-fees",
    name: "Bank Fees",
    parentId: "expense-financial",
    kind: "expense",
    icon: "receipt",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "expense-financial-loan-payment",
    name: "Loan Payment",
    parentId: "expense-financial",
    kind: "expense",
    icon: "credit-card",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "expense-others",
    name: "Others",
    parentId: null,
    kind: "expense",
    icon: "more-horizontal",
    color: "slate",
    isLeaf: false,
  },
  {
    id: "expense-others-charity",
    name: "Charity",
    parentId: "expense-others",
    kind: "expense",
    icon: "heart-handshake",
    color: "slate",
    isLeaf: true,
  },
  {
    id: "expense-others-gifts",
    name: "Gifts",
    parentId: "expense-others",
    kind: "expense",
    icon: "gift",
    color: "slate",
    isLeaf: true,
  },
  {
    id: "expense-others-miscellaneous",
    name: "Miscellaneous",
    parentId: "expense-others",
    kind: "expense",
    icon: "tag",
    color: "slate",
    isLeaf: true,
  },
] as const satisfies readonly CanonicalCategory[];
