import type { CanonicalCategory } from "@/lib/catalog/types";

export const incomeCatalog = [
  {
    id: "income-salary",
    name: "Salary",
    parentId: null,
    kind: "income",
    icon: "briefcase",
    color: "emerald",
    isLeaf: true,
  },
  {
    id: "income-business",
    name: "Business",
    parentId: null,
    kind: "income",
    icon: "store",
    color: "emerald",
    isLeaf: true,
  },
  {
    id: "income-freelance",
    name: "Freelance",
    parentId: null,
    kind: "income",
    icon: "laptop",
    color: "sky",
    isLeaf: true,
  },
  {
    id: "income-investment",
    name: "Investment",
    parentId: null,
    kind: "income",
    icon: "trending-up",
    color: "violet",
    isLeaf: true,
  },
  {
    id: "income-bonus",
    name: "Bonus",
    parentId: null,
    kind: "income",
    icon: "badge-dollar-sign",
    color: "amber",
    isLeaf: true,
  },
  {
    id: "income-gift",
    name: "Gift",
    parentId: null,
    kind: "income",
    icon: "gift",
    color: "pink",
    isLeaf: true,
  },
  {
    id: "income-refund",
    name: "Refund",
    parentId: null,
    kind: "income",
    icon: "undo-2",
    color: "teal",
    isLeaf: true,
  },
  {
    id: "income-others",
    name: "Others",
    parentId: null,
    kind: "income",
    icon: "more-horizontal",
    color: "slate",
    isLeaf: true,
  },
] as const satisfies readonly CanonicalCategory[];
